apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ub
build:
  artifacts:
  - image: angryeye/heartbeat
    context: app
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*